### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by hynsdev** [tamrol077/Tamrol-Bot#3]
Ignoring exception in on_message
Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/client.py", line 333, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 79, in on_message
    if userlevel == 1:
UnboundLocalError: local variable 'userlevel' referenced before assignment

**Comment by hynsdev** [comment]
bot starts but when i type [.help] on chat i get that error

**Comment by tamrol077** [comment]
> 
> 
> bot starts but when i type [.help] on chat i get that error

Dont worry the bot works fine even with that error. Also this was an old script I made so its probably a nightmare of spaghetti code.
